### ISSUE TITLE
`${RELEASE}` build-arg name can be "dangerous"

### ISSUE THREAD

**Issue by webknjaz** [pyca/infra#338]
So I was recovering support for manylinux1 for another project and I wanted to keep the build-arg so I attempted to pass it to `install_libffi.sh`. To my surprise, it kept being equal to an empty string. After some digging, I realized that `ARG` is declared before `FROM` and so it is out of scope for the build (it's vaguely documented in the docs but isn't always obvious). So I fixed this by re-declaring it after that line. So at this point, I had the following in the `Dockerfile`:
```dockerfile
ARG RELEASE
FROM quay.io/pypa/${RELEASE}
ARG RELEASE
...
RUN sh install_libffi.sh "${RELEASE}"
ADD install_openssl.sh /root/install_openssl.sh
ADD openssl-version.sh /root/openssl-version.sh
RUN sh install_openssl.sh
...
```
What could possibly go wrong? Well, that `RUN sh install_openssl.sh` kept failing with something like this:
```console
--> 45c19e24b84
STEP 12: RUN sh install_openssl.sh manylinux1
+ OPENSSL_URL=https://www.openssl.org/source/
+ source /root/openssl-version.sh
++ export OPENSSL_VERSION=openssl-1.1.1h
++ OPENSSL_VERSION=openssl-1.1.1h
++ export OPENSSL_SHA256=5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d
755a06595d9
++ OPENSSL_SHA256=5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d755a065
95d9
++ export 'OPENSSL_BUILD_FLAGS_WINDOWS=no-ssl3 no-ssl3-method no-zlib no-share
d no-comp no-dynamic-engine'
++ OPENSSL_BUILD_FLAGS_WINDOWS='no-ssl3 no-ssl3-method no-zlib no-shared no-co
mp no-dynamic-engine'
++ export 'OPENSSL_BUILD_FLAGS=no-ssl3 no-ssl3-method no-zlib no-shared no-com
p no-dynamic-engine enable-ec_nistp_64_gcc_128'
++ OPENSSL_BUILD_FLAGS='no-ssl3 no-ssl3-method no-zlib no-shared no-comp no-dy
namic-engine enable-ec_nistp_64_gcc_128'
+ curl -#O https://www.openssl.org/source//openssl-1.1.1h.tar.gz
####################################################################### 100.0%
+ check_sha256sum openssl-1.1.1h.tar.gz 5c9ca8774bd7b03e5784f26ae9e9e6d749c9da
2438545077e6b3d755a06595d9
+ local fname=openssl-1.1.1h.tar.gz
+ local sha256=5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d755a06595d
9
+ echo '5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d755a06595d9  open
ssl-1.1.1h.tar.gz'
+ sha256sum -c openssl-1.1.1h.tar.gz.sha256
openssl-1.1.1h.tar.gz: OK
+ rm openssl-1.1.1h.tar.gz.sha256
+ tar zxf openssl-1.1.1h.tar.gz
+ PATH=/opt/perl/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/lo
cal/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ pushd openssl-1.1.1h
~/openssl-1.1.1h ~
+ ./config no-ssl3 no-ssl3-method no-zlib no-shared no-comp no-dynamic-engine 
enable-ec_nistp_64_gcc_128 --prefix=/opt/pyca/cryptography/openssl --openssldi
r=/opt/pyca/cryptography/openssl
Operating system: x86_64-whatever-Linux
This system (Linux) is not supported. See file INSTALL for details.
Error: error building at STEP "RUN sh install_openssl.sh manylinux1": error while running runtime: exit status 1
```
WAAAAAAAT?
I had no idea why this was happening so I tried different things like downgrading openssl and comparing to old-and-working dockerfiles.
After a while, it struck me: it seems like some build script internals of OpenSSL itself relied on the `${RELEASE}` env vars somewhere internally, and re-exposing it with the second `ARG` made it available and set to some unsupported value during build-time. _And **that is** why it kept failing._ :exploding_head:

So I just wanted to document that there's a mysterious connection between `${RELEASE}` and `install_openssl.sh` (the `make` invocation inside really) that can be implicitly triggered by adding that second `ARG` instruction.
I've patched it for myself by unsetting `RELEASE` at the beginning of the script:
```diff
diff --git a/cryptography-manylinux/install_openssl.sh b/cryptography-manylinux/install_openssl.sh
index d3f7789..d0618b3 100755
--- a/cryptography-manylinux/install_openssl.sh
+++ b/cryptography-manylinux/install_openssl.sh
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -xe
 
+unset RELEASE
+
 OPENSSL_URL="https://www.openssl.org/source/"
 source /root/openssl-version.sh
```

I figured that you may want to use that build-arg as a conditional in the future and wanted to prevent others from stepping on the same rake. That said, you may want to consider either renaming this var to be something more unique (maybe `PYCA_`-prefixed) or injecting those `unset` instructions into the scripts urging people not to remove them.

You may also choose not to care about this corner case which is fine. FWIW my job here is done, the main motivation was to document this.

**Comment by alex** [comment]
Thanks for letting us know. I think for now we're not going to take any action (though I'm lazy and would probably merge a PR if someone else wrote it). We do appreciate the detailed write up, and at the very least I'm confident I'll remember this when I break it in the future in precisely the way you indicated :-)

**Comment by webknjaz** [comment]
> though I'm lazy and would probably merge a PR if someone else wrote it

Here you go: https://github.com/pyca/infra/pull/344
